-- SQL Insert Statements for 40 Story Books
-- For user: zaiaegaming@gmail.com
-- Generated on: 2025-01-20

-- First, let's get the user ID for zaiaegaming@gmail.com
-- This query should be run first to get the user_id
-- SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com';

-- For this script, we'll use a variable approach
-- Replace 'USER_ID_HERE' with the actual UUID from the query above

-- Insert Categories first (if they don't exist)
INSERT INTO categories (id, name, description, slug, is_active, created_at) VALUES
(gen_random_uuid(), 'Fantasy', 'Fantasy and magical stories', 'fantasy', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Romance', 'Love and romantic stories', 'romance', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mystery', 'Mystery and detective stories', 'mystery', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Science Fiction', 'Sci-fi and futuristic stories', 'science-fiction', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Horror', 'Horror and thriller stories', 'horror', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Adventure', 'Adventure and action stories', 'adventure', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Drama', 'Drama and emotional stories', 'drama', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Comedy', 'Comedy and humorous stories', 'comedy', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Young Adult', 'Young adult fiction', 'young-adult', true, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Thriller', 'Thriller and suspense stories', 'thriller', true, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;

-- Now insert the 40 stories
-- Note: Replace the author_id with the actual UUID of zaiaegaming@gmail.com user

INSERT INTO stories (
    id, 
    author_id, 
    title, 
    description, 
    category_id, 
    pricing_type, 
    book_status, 
    publish_status,
    total_likes, 
    total_views, 
    total_chapters,
    created_at, 
    updated_at,
    published_at
) VALUES

-- Story 1: Fantasy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Last Dragon Keeper', 
'In a world where dragons have vanished, young Aria discovers she possesses the ancient power to communicate with the last remaining dragon. Together, they must uncover the truth behind the dragons'' disappearance and save their realm from an ancient evil that threatens to consume everything.', 
(SELECT id FROM categories WHERE slug = 'fantasy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1247, 
15632, 
23,
'2025-01-15 10:30:00', 
'2025-01-19 14:22:00',
'2025-01-15 10:30:00'),

-- Story 2: Romance
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Coffee Shop Chronicles', 
'Emma, a struggling writer, finds herself falling for the mysterious barista at her local coffee shop. But when she discovers his secret past, she must decide if love is worth the risk. A heartwarming tale of second chances and unexpected romance.', 
(SELECT id FROM categories WHERE slug = 'romance'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
2156, 
28945, 
18,
'2025-01-08 09:15:00', 
'2025-01-18 16:45:00',
'2025-01-08 09:15:00'),

-- Story 3: Mystery
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Midnight Detective', 
'Detective Sarah Chen specializes in cases that occur only at midnight. When a series of impossible crimes plague the city, she must use her unique skills to solve mysteries that defy logic and reason. Each case brings her closer to a truth that could change everything.', 
(SELECT id FROM categories WHERE slug = 'mystery'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
892, 
12456, 
15,
'2025-01-12 22:00:00', 
'2025-01-19 11:30:00',
'2025-01-12 22:00:00'),

-- Story 4: Science Fiction
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Neural Network', 
'In 2087, humanity has merged with AI through neural implants. When hacker Zoe discovers a conspiracy to control human consciousness, she must navigate a digital world where thoughts become weapons and memories can be stolen.', 
(SELECT id FROM categories WHERE slug = 'science-fiction'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1834, 
22187, 
27,
'2025-01-05 14:20:00', 
'2025-01-19 09:15:00',
'2025-01-05 14:20:00'),

-- Story 5: Horror
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Whispering House', 
'The Blackwood family inherits an old Victorian mansion, but they soon discover that the house has a dark history. As whispers in the walls grow louder and shadows move on their own, they must uncover the truth before the house claims them as its next victims.', 
(SELECT id FROM categories WHERE slug = 'horror'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
3421, 
41256, 
22,
'2025-01-03 20:45:00', 
'2025-01-17 13:20:00',
'2025-01-03 20:45:00'),

-- Story 6: Adventure
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Treasure of the Seven Seas', 
'Captain Maya Rodriguez leads her crew on a quest to find the legendary treasure of the Seven Seas. Facing storms, sea monsters, and rival pirates, they must work together to overcome impossible odds and claim the greatest prize in maritime history.', 
(SELECT id FROM categories WHERE slug = 'adventure'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
967, 
18743, 
19,
'2025-01-10 11:00:00', 
'2025-01-19 15:30:00',
'2025-01-10 11:00:00'),

-- Story 7: Drama
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Broken Melodies', 
'Former concert pianist Elena must rebuild her life after a career-ending injury. Through teaching music to underprivileged children, she discovers that sometimes the most beautiful melodies come from the most broken places.', 
(SELECT id FROM categories WHERE slug = 'drama'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
2789, 
35642, 
16,
'2025-01-07 16:30:00', 
'2025-01-16 10:45:00',
'2025-01-07 16:30:00'),

-- Story 8: Comedy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Accidental Superhero', 
'Mild-mannered accountant Bob accidentally gains superpowers after a freak accident with a microwave and a radioactive burrito. Now he must learn to be a hero while keeping his day job and hiding his secret from his overbearing mother.', 
(SELECT id FROM categories WHERE slug = 'comedy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1456, 
19834, 
21,
'2025-01-11 13:15:00', 
'2025-01-19 12:00:00',
'2025-01-11 13:15:00'),

-- Story 9: Young Adult
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'High School Time Loop', 
'Sixteen-year-old Alex is stuck reliving the same day at high school over and over again. To break the loop, they must solve the mystery of why time stopped and learn valuable lessons about friendship, love, and growing up.', 
(SELECT id FROM categories WHERE slug = 'young-adult'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2134, 
27891, 
14,
'2025-01-13 08:45:00', 
'2025-01-19 17:20:00',
'2025-01-13 08:45:00'),

-- Story 10: Thriller
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Memory Thief', 
'Psychologist Dr. Amanda Cross can steal and manipulate memories. When she becomes the target of a serial killer who erases his victims'' memories before killing them, she must use her dangerous ability to catch him before she becomes his next victim.', 
(SELECT id FROM categories WHERE slug = 'thriller'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
3876, 
48923, 
20,
'2025-01-02 19:30:00', 
'2025-01-15 14:15:00',
'2025-01-02 19:30:00'),

-- Story 11: Fantasy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Enchanted Library', 
'Librarian Lily discovers that her small-town library is actually a gateway to magical worlds. Each book she opens transports her to different realms where she must help solve problems and restore balance between the magical and mundane worlds.', 
(SELECT id FROM categories WHERE slug = 'fantasy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1623, 
21456, 
25,
'2025-01-06 12:20:00', 
'2025-01-19 10:45:00',
'2025-01-06 12:20:00'),

-- Story 12: Romance
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Second Chance Summer', 
'Ten years after their messy breakup, childhood sweethearts Jake and Sophie are forced to work together to save their hometown''s annual summer festival. Old feelings resurface as they rediscover what they meant to each other.', 
(SELECT id FROM categories WHERE slug = 'romance'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
2945, 
38764, 
17,
'2025-01-04 15:10:00', 
'2025-01-18 11:30:00',
'2025-01-04 15:10:00'),

-- Story 13: Mystery
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Vanishing Artist', 
'Art curator Marcus investigates the mysterious disappearance of a famous painter whose final masterpiece seems to predict future crimes. As he delves deeper into the art world''s secrets, he realizes the painting might be more than just art.', 
(SELECT id FROM categories WHERE slug = 'mystery'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1178, 
16892, 
13,
'2025-01-14 17:25:00', 
'2025-01-19 13:40:00',
'2025-01-14 17:25:00'),

-- Story 14: Science Fiction
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Colony Ship Exodus', 
'On a generation ship traveling to a distant planet, engineer Rosa discovers that their destination may not be what they were promised. With limited resources and growing unrest, she must uncover the truth about their mission before it''s too late.', 
(SELECT id FROM categories WHERE slug = 'science-fiction'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
2567, 
32145, 
29,
'2025-01-01 10:00:00', 
'2025-01-19 16:15:00',
'2025-01-01 10:00:00'),

-- Story 15: Horror
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Night Shift', 
'Hospital nurse David works the graveyard shift where strange things happen after midnight. Patients who should be dead walk the halls, and shadows move independently. He must uncover the hospital''s dark secret before he becomes its next victim.', 
(SELECT id FROM categories WHERE slug = 'horror'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2234, 
29876, 
18,
'2025-01-09 21:15:00', 
'2025-01-19 14:50:00',
'2025-01-09 21:15:00'),

-- Story 16: Adventure
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Lost City of Atlantis', 
'Marine archaeologist Dr. Elena Vasquez leads an expedition to find the lost city of Atlantis. When they discover it''s not just a myth but a thriving underwater civilization, they must navigate political intrigue and ancient technology to prevent a war between two worlds.', 
(SELECT id FROM categories WHERE slug = 'adventure'), 
'FREE', 
'COMPLETED', 
'PUBLISHED',
3145, 
42387, 
24,
'2025-01-01 14:30:00', 
'2025-01-17 09:20:00',
'2025-01-01 14:30:00'),

-- Story 17: Drama
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Last Letter', 
'When elderly Margaret finds a box of unsent letters in her attic, she embarks on a journey to deliver them to their intended recipients. Each letter reveals a piece of her past and helps heal old wounds while creating new connections.', 
(SELECT id FROM categories WHERE slug = 'drama'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
1876, 
25643, 
15,
'2025-01-05 11:45:00', 
'2025-01-16 15:30:00',
'2025-01-05 11:45:00'),

-- Story 18: Comedy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'My Roommate is an Alien', 
'College student Chris discovers his weird roommate is actually an alien studying human behavior for his thesis. Together they navigate college life, dating, and the occasional intergalactic incident while keeping the alien''s identity secret.', 
(SELECT id FROM categories WHERE slug = 'comedy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1789, 
23456, 
16,
'2025-01-12 09:30:00', 
'2025-01-19 11:15:00',
'2025-01-12 09:30:00'),

-- Story 19: Young Adult
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Popularity Algorithm', 
'Tech-savvy teenager Maya creates an app that predicts social popularity, but when it starts controlling people''s behavior, she must find a way to shut it down before it destroys her school''s social fabric and her friendships.', 
(SELECT id FROM categories WHERE slug = 'young-adult'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2456, 
31789, 
12,
'2025-01-15 16:20:00', 
'2025-01-19 18:45:00',
'2025-01-15 16:20:00'),

-- Story 20: Thriller
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Perfect Neighbor', 
'When the Johnsons move to a quiet suburban neighborhood, they think they''ve found paradise. But their friendly neighbor harbors a dark secret, and soon they realize that everyone on the street is hiding something deadly.', 
(SELECT id FROM categories WHERE slug = 'thriller'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
4123, 
52876, 
19,
'2025-01-03 13:45:00', 
'2025-01-18 12:10:00',
'2025-01-03 13:45:00'),

-- Story 21: Fantasy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Spell Weaver''s Apprentice', 
'Young Kai becomes apprentice to the last Spell Weaver in the kingdom. When dark magic threatens to destroy the realm, he must master ancient spells and forge unlikely alliances to save his world from eternal darkness.', 
(SELECT id FROM categories WHERE slug = 'fantasy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1534, 
20187, 
22,
'2025-01-08 14:15:00', 
'2025-01-19 15:25:00',
'2025-01-08 14:15:00'),

-- Story 22: Romance
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Love in the Time of Startups', 
'Ambitious entrepreneur Sarah and laid-back developer Tom are forced to work together on a revolutionary app. As their professional relationship evolves into something more, they must navigate the challenges of love and business in Silicon Valley.', 
(SELECT id FROM categories WHERE slug = 'romance'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2678, 
34521, 
14,
'2025-01-11 10:30:00', 
'2025-01-19 12:45:00',
'2025-01-11 10:30:00'),

-- Story 23: Mystery
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Clockmaker''s Secret', 
'Antique dealer Emma inherits a mysterious clock shop where each timepiece holds a secret from the past. When people start disappearing, she discovers the clocks are connected to unsolved crimes spanning decades.', 
(SELECT id FROM categories WHERE slug = 'mystery'), 
'FREE', 
'COMPLETED', 
'PUBLISHED',
2145, 
28934, 
21,
'2025-01-06 18:20:00', 
'2025-01-17 14:35:00',
'2025-01-06 18:20:00'),

-- Story 24: Science Fiction
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'Quantum Entanglement', 
'Physicist Dr. Lisa Chen discovers she can communicate with alternate versions of herself across parallel universes. When a catastrophic event threatens all realities, she must coordinate with her other selves to prevent universal collapse.', 
(SELECT id FROM categories WHERE slug = 'science-fiction'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
1923, 
26745, 
26,
'2025-01-04 12:10:00', 
'2025-01-19 09:30:00',
'2025-01-04 12:10:00'),

-- Story 25: Horror
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Doll Collector', 
'Antique doll restorer Maria receives a collection of vintage dolls with a disturbing history. As the dolls begin to move on their own and whisper secrets from beyond the grave, she must uncover their tragic past before they claim her soul.', 
(SELECT id FROM categories WHERE slug = 'horror'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
3567, 
45123, 
17,
'2025-01-02 16:45:00', 
'2025-01-16 11:20:00',
'2025-01-02 16:45:00'),

-- Story 26: Adventure
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Sky Pirates', 
'In a world of floating islands, airship captain Zara leads her crew of sky pirates on daring heists. When they discover a plot to destroy the sky cities, they must choose between their criminal lifestyle and saving their world.', 
(SELECT id FROM categories WHERE slug = 'adventure'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1345, 
19876, 
20,
'2025-01-13 15:40:00', 
'2025-01-19 16:55:00',
'2025-01-13 15:40:00'),

-- Story 27: Drama
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Art of Forgiveness', 
'After a tragic accident tears their family apart, the Hendersons must learn to forgive each other and themselves. Through therapy, love, and understanding, they discover that healing is possible even after the deepest wounds.', 
(SELECT id FROM categories WHERE slug = 'drama'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
2234, 
31567, 
18,
'2025-01-07 13:25:00', 
'2025-01-18 10:15:00',
'2025-01-07 13:25:00'),

-- Story 28: Comedy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Wedding Planner''s Nightmare', 
'Wedding planner Jessica''s biggest event turns into chaos when everything that can go wrong does. From runaway brides to cake disasters, she must use her wit and creativity to save the day and her reputation.', 
(SELECT id FROM categories WHERE slug = 'comedy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1678, 
22134, 
15,
'2025-01-10 11:50:00', 
'2025-01-19 13:20:00',
'2025-01-10 11:50:00'),

-- Story 29: Young Adult
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Invisible Girl', 
'Shy teenager Luna discovers she can become invisible when she feels ignored. As she uses her power to help others and gain confidence, she learns that being seen isn''t about being visible—it''s about being authentic.', 
(SELECT id FROM categories WHERE slug = 'young-adult'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2789, 
36421, 
11,
'2025-01-16 14:30:00', 
'2025-01-19 17:45:00',
'2025-01-16 14:30:00'),

-- Story 30: Thriller
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Identity Thief', 
'FBI agent Rachel discovers someone is stealing identities and living entire lives as other people. When she realizes the thief has targeted her own identity, she must catch them before they destroy everything she''s worked for.', 
(SELECT id FROM categories WHERE slug = 'thriller'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
3234, 
41789, 
23,
'2025-01-05 09:15:00', 
'2025-01-19 14:30:00',
'2025-01-05 09:15:00'),

-- Story 31: Fantasy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Phoenix Rising', 
'When the last phoenix dies, the magical world begins to fade. Young mage Ember must journey to the realm of the dead to retrieve the phoenix''s soul and restore magic to her dying world, facing her own mortality in the process.', 
(SELECT id FROM categories WHERE slug = 'fantasy'), 
'FREE', 
'COMPLETED', 
'PUBLISHED',
2456, 
33678, 
28,
'2025-01-01 16:20:00', 
'2025-01-18 15:45:00',
'2025-01-01 16:20:00'),

-- Story 32: Romance
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Food Truck Romance', 
'Chef Miguel and food blogger Anna compete for the same prime location for their businesses. Their rivalry turns to romance as they discover their shared passion for food and helping their community through culinary arts.', 
(SELECT id FROM categories WHERE slug = 'romance'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
1987, 
27543, 
16,
'2025-01-09 12:40:00', 
'2025-01-17 16:25:00',
'2025-01-09 12:40:00'),

-- Story 33: Mystery
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Bookstore Murder', 
'Bookstore owner Claire finds a dead body in her rare books section. As the prime suspect, she must solve the murder herself, using clues hidden in classic literature to uncover a conspiracy that reaches the highest levels of society.', 
(SELECT id FROM categories WHERE slug = 'mystery'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1456, 
20345, 
17,
'2025-01-12 17:15:00', 
'2025-01-19 11:40:00',
'2025-01-12 17:15:00'),

-- Story 34: Science Fiction
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Time Merchant', 
'In a future where time can be bought and sold, black market time dealer Alex discovers that someone is stealing years from people''s lives. He must navigate a dangerous underworld to stop the time thief before humanity runs out of time.', 
(SELECT id FROM categories WHERE slug = 'science-fiction'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
2134, 
29876, 
24,
'2025-01-07 10:25:00', 
'2025-01-19 12:50:00',
'2025-01-07 10:25:00'),

-- Story 35: Horror
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Haunted Podcast', 
'Paranormal investigator Sam starts a podcast about haunted locations, but when listeners begin experiencing supernatural events after each episode, he realizes his show is opening doorways to the other side.', 
(SELECT id FROM categories WHERE slug = 'horror'), 
'PAID_PER_CHAPTER', 
'ONGOING', 
'PUBLISHED',
2876, 
37654, 
19,
'2025-01-08 19:30:00', 
'2025-01-19 15:10:00',
'2025-01-08 19:30:00'),

-- Story 36: Adventure
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Jungle Explorer', 
'Wildlife photographer Maya ventures into an uncharted Amazon rainforest and discovers a hidden civilization that has lived in harmony with nature for centuries. She must protect their secret from the outside world while documenting their way of life.', 
(SELECT id FROM categories WHERE slug = 'adventure'), 
'FREE', 
'COMPLETED', 
'PUBLISHED',
1723, 
24567, 
22,
'2025-01-04 08:45:00', 
'2025-01-16 13:30:00',
'2025-01-04 08:45:00'),

-- Story 37: Drama
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Teacher''s Legacy', 
'Veteran teacher Mrs. Rodriguez faces retirement as her inner-city school faces closure. In her final year, she fights to save the school while inspiring a new generation of students to believe in themselves and their dreams.', 
(SELECT id FROM categories WHERE slug = 'drama'), 
'WHOLE_BOOK', 
'COMPLETED', 
'PUBLISHED',
3145, 
41234, 
20,
'2025-01-03 11:15:00', 
'2025-01-17 09:45:00',
'2025-01-03 11:15:00'),

-- Story 38: Comedy
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Substitute Teacher', 
'Unemployed actor Danny takes a job as a substitute teacher and discovers that managing a classroom is harder than performing Shakespeare. Through comedy and chaos, he learns valuable lessons about education and finds his true calling.', 
(SELECT id FROM categories WHERE slug = 'comedy'), 
'FREE', 
'ONGOING', 
'PUBLISHED',
1234, 
18765, 
13,
'2025-01-14 10:20:00', 
'2025-01-19 14:15:00',
'2025-01-14 10:20:00'),

-- Story 39: Young Adult
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Social Media Detox', 
'When seventeen-year-old Zoe''s phone breaks, she''s forced to go a month without social media. During her digital detox, she rediscovers real friendships, develops new hobbies, and learns that life is more meaningful offline.', 
(SELECT id FROM categories WHERE slug = 'young-adult'), 
'PAID_PER_CHAPTER', 
'COMPLETED', 
'PUBLISHED',
2567, 
34123, 
14,
'2025-01-06 15:50:00', 
'2025-01-18 12:35:00',
'2025-01-06 15:50:00'),

-- Story 40: Thriller
(gen_random_uuid(), 
(SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com'), 
'The Digital Stalker', 
'Cybersecurity expert Nina discovers someone is using advanced AI to stalk and manipulate people online. When she becomes the stalker''s next target, she must use all her technical skills to unmask the predator before they destroy her life.', 
(SELECT id FROM categories WHERE slug = 'thriller'), 
'WHOLE_BOOK', 
'ONGOING', 
'PUBLISHED',
3456, 
44789, 
21,
'2025-01-02 14:10:00', 
'2025-01-19 16:20:00',
'2025-01-02 14:10:00');

-- Update story ratings (adding average rating between 3.5 and 5.0)
-- Note: This assumes you have a ratings table or rating field in stories table
-- If you have a separate ratings table, you'll need to create rating records instead

-- Optional: Add some additional metadata updates
UPDATE stories SET 
    total_want_to_read = FLOOR(total_views * 0.15 + RANDOM() * total_views * 0.1),
    total_completed = FLOOR(total_views * 0.08 + RANDOM() * total_views * 0.05),
    total_currently_reading = FLOOR(total_views * 0.12 + RANDOM() * total_views * 0.08),
    total_comments = FLOOR(total_likes * 0.3 + RANDOM() * total_likes * 0.2)
WHERE author_id = (SELECT id FROM users WHERE email = 'zaiaegaming@gmail.com');

-- Summary of the 40 stories created:
-- Fantasy: 4 stories (The Last Dragon Keeper, The Enchanted Library, The Spell Weaver's Apprentice, The Phoenix Rising)
-- Romance: 4 stories (Coffee Shop Chronicles, Second Chance Summer, Love in the Time of Startups, The Food Truck Romance)
-- Mystery: 4 stories (The Midnight Detective, The Vanishing Artist, The Clockmaker's Secret, The Bookstore Murder)
-- Science Fiction: 4 stories (Neural Network, Colony Ship Exodus, Quantum Entanglement, The Time Merchant)
-- Horror: 4 stories (The Whispering House, The Night Shift, The Doll Collector, The Haunted Podcast)
-- Adventure: 4 stories (Treasure of the Seven Seas, The Lost City of Atlantis, The Sky Pirates, The Jungle Explorer)
-- Drama: 4 stories (Broken Melodies, The Last Letter, The Art of Forgiveness, The Teacher's Legacy)
-- Comedy: 4 stories (The Accidental Superhero, My Roommate is an Alien, The Wedding Planner's Nightmare, The Substitute Teacher)
-- Young Adult: 4 stories (High School Time Loop, The Popularity Algorithm, The Invisible Girl, The Social Media Detox)
-- Thriller: 4 stories (The Memory Thief, The Perfect Neighbor, The Identity Thief, The Digital Stalker)

-- Pricing distribution:
-- FREE: 13 stories
-- PAID_PER_CHAPTER: 14 stories  
-- WHOLE_BOOK: 13 stories

-- Status distribution:
-- ONGOING: 24 stories
-- COMPLETED: 16 stories

-- Upload dates range from 2025-01-01 to 2025-01-19
-- Views range from ~12,000 to ~53,000
-- Likes range from ~892 to ~4,123
-- All stories are set to PUBLISHED status